- hosts: localhost  #在本地运行
  connection: local
  become: true

  pre_task:
    - name: update repostoruies
    apt:
      update_cache: yes
    changed_when: Flase

  tasks:
    - include: tasks/user.yml
    - include: tasks/packages.yml
    


  